import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { Providers } from "@/store/Providers";

const prompt = Prompt({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={prompt.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
